version: '2'
services:
    ng2jh-mysql:
        container_name: ng2jh-mysql
        image: mysql:5.7.13
        # volumes:
        #     - ~/volumes/jhipster/ng2jh/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=ng2jh
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8
